# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d5f4e1ba2a092a1545ef3072e509ae4e69a1b3cc439f90c681850d8c664b753ccda6bce40175996cf208f22ce45e14dbea6f3edb782d7e59d9c61b2670e8f35

test:
  secret_key_base: c9429e1baad0e7054170b8187698cb9220ba36f5579bc5d8b9385c2abcf1cc5c5d098a42992fdf34c0df9566f7c0056b3ce3ccc9ef725f1b69668320abeda24c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
